---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt -g
  - phantomjs-prebuilt --version

install:
  - npm install
  - bower install
  - npm build

script:
  - npm test
