---
language: node_js
node_js:
  - "10"

sudo: false
dist: trusty

services:
  - xvfb

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

before_script:
  - export DISPLAY=:99.0

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    
addons:
  firefox: latest

script:
  - npm test
