---
language: node_js
node_js:
  - "10"

env:
  - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
addons:
  firefox: latest
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - gcc-4.9

os:
  - linux
  - osx

sudo: false

services:
  - xvfb

cache:
  directories:
  - node_modules
  - bower_components
  - $HOME/.npm
  - $HOME/.cache # includes bowers cache
  - cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version

install:
  - npm install
  - bower install

before_script:
  - export DISPLAY=:99.0

addons:
  firefox: latest

script:
  - npm test

before_deploy: 
  - wget -O app/components/descripcion-acerca-de.js https://raw.githubusercontent.com/Program-AR/pilas-bloques/master/app/components/descripcion-acerca-de.js
  - wget -O app/templates/components/descripcion-acerca-de.hbs https://raw.githubusercontent.com/Program-AR/pilas-bloques/master/app/templates/components/descripcion-acerca-de.hbs
  - ./node_modules/.bin/ember build --environment development
deploy:
  provider: surge # Whenever master gets updated, update surge site.
  project: ./dist/
  domain: sitepilasbloques.surge.sh
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_OS_NAME == linux"