name: build
on: [push]
jobs:
  #Copypasted from https://github.com/Program-AR/pilas-bloques/blob/develop/.github/workflows/build.yml
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1

      #https://docs.github.com/es/actions/guides/caching-dependencies-to-speed-up-workflows#using-the-cache-action
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: npm install

      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: npm run test

  package-site:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
      - run: npm run package:site
      - uses: ncipollo/release-action@v1
    with:
      artifact: sitepilasbloques.tar.gz
      token: ${{ secrets.GITHUB_TOKEN }}
